-- Seed Data: 50 Esports & Gaming Industry Careers
-- Description: Real careers in the esports and gaming industry
-- Generated: 2025-10-29
-- Source: Industry data, esports salary surveys
--
-- Note: O*NET codes removed since these are gaming-specific careers

-- Clean all existing career data
-- Note: We set career_id to NULL in pathkeys first to avoid CASCADE deletion
UPDATE public.pathkeys SET career_id = NULL WHERE career_id IS NOT NULL;
TRUNCATE TABLE public.careers RESTART IDENTITY;

-- Insert 50 gaming/esports careers
INSERT INTO public.careers (
  onet_code,
  title,
  description,
  industry,
  sector,
  career_cluster,
  education_level,
  certifications,
  skills,
  salary_min,
  salary_max,
  salary_median,
  growth_rate,
  job_outlook,
  tasks,
  work_environment,
  is_verified,
  content_last_updated
) VALUES

-- ESPORTS OPERATIONS (Team/Player Management)
(
  NULL,
  'Esports Agent',
  'Represent professional esports players and content creators. Negotiate contracts, sponsorships, and endorsement deals while managing career development and public relations.',
  'Esports',
  'Esports Operations',
  'Business Management & Administration',
  ARRAY['Bachelor''s Degree'],
  ARRAY['Sports Agent Certification', 'Contract Law'],
  '[{"name": "Negotiation", "level": 5}, {"name": "Contract Management", "level": 5}, {"name": "Industry Knowledge", "level": 5}, {"name": "Networking", "level": 4}]'::jsonb,
  45000,
  150000,
  75000,
  25.0,
  'Much faster than average - Esports industry is booming',
  ARRAY['Negotiate player contracts and endorsements', 'Build relationships with teams and sponsors', 'Manage player schedules and appearances', 'Handle legal and financial matters', 'Develop player brand strategy'],
  'Mix of office work and event travel. Irregular hours due to international tournaments and streaming schedules.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Head Coach',
  'Lead esports team to competitive success. Develop strategies, analyze opponent gameplay, conduct practice sessions, and make critical in-game decisions.',
  'Esports',
  'Esports Operations',
  'Education & Training',
  ARRAY['Bachelor''s Degree', 'High School Diploma'],
  ARRAY['Game-Specific Certifications', 'Leadership Training'],
  '[{"name": "Game Strategy", "level": 5}, {"name": "Leadership", "level": 5}, {"name": "Communication", "level": 5}, {"name": "Analytics", "level": 4}]'::jsonb,
  50000,
  250000,
  95000,
  30.0,
  'Much faster than average - Professional teams expanding globally',
  ARRAY['Analyze gameplay footage and develop strategies', 'Conduct team practice and scrimmages', 'Scout opponents and prepare game plans', 'Make roster and draft decisions', 'Manage team morale and dynamics'],
  'Gaming house or team facility. Long hours including evenings and weekends. Travel to tournaments.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Esports Asst Coach',
  'Support head coach in player development and strategy. Specialize in specific roles or game mechanics while managing practice schedules.',
  'Esports',
  'Esports Operations',
  'Education & Training',
  ARRAY['Bachelor''s Degree', 'Associate''s Degree'],
  ARRAY['Game-Specific Certifications'],
  '[{"name": "Game Knowledge", "level": 5}, {"name": "Player Development", "level": 4}, {"name": "Data Analysis", "level": 4}, {"name": "Communication", "level": 4}]'::jsonb,
  35000,
  120000,
  60000,
  28.0,
  'Faster than average',
  ARRAY['Assist in developing team strategies', 'Work with individual players on mechanics', 'Review and analyze match footage', 'Coordinate practice schedules', 'Scout new talent'],
  'Team facility with flexible hours. Some travel to tournaments.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Esports Analyst',
  'Analyze gameplay data, player statistics, and opponent tendencies to provide strategic insights for coaching staff and teams.',
  'Esports',
  'Esports Operations',
  'Science, Technology, Engineering & Mathematics',
  ARRAY['Bachelor''s Degree'],
  ARRAY['Data Analytics Certification', 'Statistics'],
  '[{"name": "Data Analysis", "level": 5}, {"name": "Statistics", "level": 5}, {"name": "Game Knowledge", "level": 5}, {"name": "Communication", "level": 4}]'::jsonb,
  45000,
  110000,
  68000,
  35.0,
  'Much faster than average - Data-driven decision making is critical',
  ARRAY['Collect and analyze gameplay statistics', 'Create performance reports and visualizations', 'Identify trends and patterns in matches', 'Scout opponents and provide strategic advice', 'Develop prediction models'],
  'Office or remote work. Irregular hours during tournament seasons.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Team Manager',
  'Oversee daily operations of esports team. Manage logistics, budgets, schedules, and coordinate between players, coaches, and organization.',
  'Esports',
  'Esports Operations',
  'Business Management & Administration',
  ARRAY['Bachelor''s Degree'],
  ARRAY['Project Management Professional', 'Sports Management'],
  '[{"name": "Operations Management", "level": 5}, {"name": "Budget Management", "level": 5}, {"name": "Coordination", "level": 5}, {"name": "Problem Solving", "level": 4}]'::jsonb,
  50000,
  130000,
  75000,
  22.0,
  'Faster than average',
  ARRAY['Manage team schedules and travel logistics', 'Coordinate practice and tournament schedules', 'Handle contracts and player relations', 'Manage team budget and expenses', 'Liaise with sponsors and partners'],
  'Office and travel. Irregular hours with international tournaments.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Team Captain',
  'Lead team during matches as in-game leader. Make strategic calls, maintain team morale, and communicate with coaching staff.',
  'Esports',
  'Esports Operations',
  'Leadership',
  ARRAY['High School Diploma'],
  ARRAY['Game-Specific Achievements', 'Leadership Training'],
  '[{"name": "In-Game Leadership", "level": 5}, {"name": "Communication", "level": 5}, {"name": "Decision Making", "level": 5}, {"name": "Game Mastery", "level": 5}]'::jsonb,
  30000,
  500000,
  85000,
  25.0,
  'Much faster than average',
  ARRAY['Make strategic decisions during matches', 'Communicate effectively with teammates', 'Maintain team morale and focus', 'Review gameplay and provide feedback', 'Work with coaches on strategy'],
  'Gaming facility with intense practice schedules. Tournament travel required.',
  true,
  CURRENT_DATE
),

-- HEALTH & WELLNESS
(
  NULL,
  'Esports Nutritionist',
  'Develop nutrition plans to optimize player performance, energy levels, and mental clarity during training and competition.',
  'Esports',
  'Health & Wellness',
  'Health Science',
  ARRAY['Bachelor''s Degree', 'Master''s Degree'],
  ARRAY['Registered Dietitian', 'Sports Nutrition Specialist'],
  '[{"name": "Nutrition Science", "level": 5}, {"name": "Meal Planning", "level": 5}, {"name": "Health Education", "level": 4}, {"name": "Communication", "level": 4}]'::jsonb,
  45000,
  95000,
  62000,
  20.0,
  'Faster than average - Growing focus on player health',
  ARRAY['Create personalized nutrition plans for players', 'Educate on healthy eating and hydration', 'Monitor player health and energy levels', 'Coordinate with chefs and catering', 'Track performance metrics'],
  'Mix of office consultations and team facility visits.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Psychologist',
  'Provide mental health support, performance psychology coaching, and stress management for esports professionals.',
  'Esports',
  'Health & Wellness',
  'Health Science',
  ARRAY['Doctoral Degree', 'Master''s Degree'],
  ARRAY['Licensed Psychologist', 'Sports Psychology Certification'],
  '[{"name": "Clinical Psychology", "level": 5}, {"name": "Counseling", "level": 5}, {"name": "Performance Coaching", "level": 5}, {"name": "Empathy", "level": 5}]'::jsonb,
  60000,
  140000,
  85000,
  18.0,
  'Average - Mental health awareness increasing',
  ARRAY['Provide individual therapy sessions', 'Conduct performance psychology coaching', 'Teach stress management techniques', 'Support team dynamics and conflict resolution', 'Crisis intervention'],
  'Private office with flexible hours. Some remote sessions.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Fitness Coach',
  'Design fitness programs to improve player physical health, reduce injury risk, and enhance gaming performance through exercise.',
  'Esports',
  'Health & Wellness',
  'Health Science',
  ARRAY['Bachelor''s Degree', 'Associate''s Degree'],
  ARRAY['Certified Personal Trainer', 'Strength & Conditioning Specialist'],
  '[{"name": "Exercise Science", "level": 5}, {"name": "Program Design", "level": 5}, {"name": "Motivation", "level": 4}, {"name": "Injury Prevention", "level": 4}]'::jsonb,
  35000,
  75000,
  50000,
  15.0,
  'Average',
  ARRAY['Design customized workout programs', 'Lead team fitness sessions', 'Monitor player physical health', 'Teach proper posture and ergonomics', 'Prevent and manage gaming-related injuries'],
  'Gym or training facility. Flexible schedule around team practices.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Performance Coach',
  'Help players optimize performance through mental skills training, routine development, and competitive mindset coaching.',
  'Esports',
  'Health & Wellness',
  'Education & Training',
  ARRAY['Bachelor''s Degree', 'Master''s Degree'],
  ARRAY['Performance Psychology', 'Coaching Certification'],
  '[{"name": "Performance Psychology", "level": 5}, {"name": "Coaching", "level": 5}, {"name": "Mental Skills Training", "level": 5}, {"name": "Communication", "level": 4}]'::jsonb,
  40000,
  100000,
  60000,
  22.0,
  'Faster than average',
  ARRAY['Develop mental training programs', 'Teach focus and concentration techniques', 'Help players manage competition anxiety', 'Create pre-match routines', 'Monitor player mental state'],
  'Team facility or remote coaching. Flexible hours.',
  true,
  CURRENT_DATE
),

-- TECHNOLOGY & ENGINEERING
(
  NULL,
  'Software Engineer',
  'Develop and maintain gaming platforms, tournament systems, streaming software, and esports management tools.',
  'Gaming',
  'Technology',
  'Information Technology',
  ARRAY['Bachelor''s Degree'],
  ARRAY['AWS Certified Developer', 'Full Stack Development'],
  '[{"name": "Programming", "level": 5}, {"name": "Problem Solving", "level": 5}, {"name": "System Design", "level": 5}, {"name": "Teamwork", "level": 4}]'::jsonb,
  70000,
  180000,
  115000,
  25.0,
  'Much faster than average - Gaming tech is rapidly evolving',
  ARRAY['Design and build gaming platforms', 'Develop tournament management systems', 'Create streaming and broadcast tools', 'Optimize performance and scalability', 'Collaborate with game designers'],
  'Office or remote work. Flexible hours with deadline pressures.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Cloud Security Engineer',
  'Protect gaming infrastructure, player data, and tournament systems from cyber threats and ensure compliance.',
  'Gaming',
  'Technology',
  'Information Technology',
  ARRAY['Bachelor''s Degree'],
  ARRAY['CISSP', 'Cloud Security Certification'],
  '[{"name": "Cybersecurity", "level": 5}, {"name": "Cloud Architecture", "level": 5}, {"name": "Risk Assessment", "level": 5}, {"name": "Compliance", "level": 4}]'::jsonb,
  80000,
  170000,
  120000,
  32.0,
  'Much faster than average - Security is critical',
  ARRAY['Secure gaming platforms and infrastructure', 'Implement security protocols', 'Monitor for threats and vulnerabilities', 'Conduct security audits', 'Respond to security incidents'],
  'Office or remote work. On-call for security incidents.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'CyberSecurity Analyst',
  'Monitor and protect esports organizations from cyber attacks, data breaches, and online threats.',
  'Gaming',
  'Technology',
  'Information Technology',
  ARRAY['Bachelor''s Degree'],
  ARRAY['CompTIA Security+', 'Certified Ethical Hacker'],
  '[{"name": "Threat Detection", "level": 5}, {"name": "Security Analysis", "level": 5}, {"name": "Incident Response", "level": 5}, {"name": "Technical Skills", "level": 5}]'::jsonb,
  65000,
  140000,
  95000,
  33.0,
  'Much faster than average',
  ARRAY['Monitor security systems and alerts', 'Investigate security incidents', 'Implement security measures', 'Conduct vulnerability assessments', 'Train staff on security practices'],
  'Office or remote work. May require on-call hours.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'IT Coordinator',
  'Manage technology infrastructure for esports teams and events. Ensure reliable internet, hardware, and software systems.',
  'Gaming',
  'Technology',
  'Information Technology',
  ARRAY['Bachelor''s Degree', 'Associate''s Degree'],
  ARRAY['CompTIA A+', 'Network+'],
  '[{"name": "Network Administration", "level": 5}, {"name": "Hardware Troubleshooting", "level": 5}, {"name": "Problem Solving", "level": 4}, {"name": "Communication", "level": 4}]'::jsonb,
  45000,
  95000,
  65000,
  15.0,
  'Average',
  ARRAY['Maintain team and event IT infrastructure', 'Troubleshoot technical issues', 'Manage network and hardware', 'Support players and staff with tech', 'Coordinate with vendors'],
  'Mix of office and on-site at tournaments. May require travel.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Tech Support',
  'Provide technical assistance to players, staff, and fans. Troubleshoot gaming equipment, software, and connectivity issues.',
  'Gaming',
  'Technology',
  'Information Technology',
  ARRAY['Associate''s Degree', 'High School Diploma'],
  ARRAY['CompTIA A+', 'Customer Service'],
  '[{"name": "Technical Troubleshooting", "level": 5}, {"name": "Customer Service", "level": 5}, {"name": "Communication", "level": 4}, {"name": "Patience", "level": 4}]'::jsonb,
  35000,
  70000,
  48000,
  10.0,
  'Average',
  ARRAY['Respond to technical support requests', 'Troubleshoot hardware and software issues', 'Assist with gaming equipment setup', 'Document and resolve technical problems', 'Train users on systems'],
  'Office or remote support center. Flexible hours.',
  true,
  CURRENT_DATE
),

-- CREATIVE & MEDIA
(
  NULL,
  '3D Artist',
  'Create 3D models, textures, and animations for games, marketing materials, and broadcast graphics.',
  'Gaming',
  'Creative & Media',
  'Arts, Audio/Video Technology & Communications',
  ARRAY['Bachelor''s Degree'],
  ARRAY['Autodesk Certified', 'Unreal Engine'],
  '[{"name": "3D Modeling", "level": 5}, {"name": "Texturing", "level": 5}, {"name": "Animation", "level": 4}, {"name": "Creativity", "level": 5}]'::jsonb,
  45000,
  110000,
  68000,
  16.0,
  'Average',
  ARRAY['Create 3D models for games and media', 'Texture and light 3D assets', 'Animate characters and objects', 'Collaborate with designers and developers', 'Optimize models for performance'],
  'Studio or remote work. Project-based deadlines.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Graphic Designer',
  'Design visual content for teams, tournaments, social media, merchandise, and marketing campaigns.',
  'Gaming',
  'Creative & Media',
  'Arts, Audio/Video Technology & Communications',
  ARRAY['Bachelor''s Degree'],
  ARRAY['Adobe Creative Suite', 'Design Certification'],
  '[{"name": "Graphic Design", "level": 5}, {"name": "Branding", "level": 5}, {"name": "Creativity", "level": 5}, {"name": "Communication", "level": 4}]'::jsonb,
  40000,
  90000,
  58000,
  13.0,
  'Average',
  ARRAY['Design team logos and branding', 'Create social media graphics', 'Design merchandise and apparel', 'Develop marketing materials', 'Maintain brand consistency'],
  'Office or remote work. Fast-paced with quick turnarounds.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Videographer',
  'Capture and produce video content including highlights, documentaries, player interviews, and promotional materials.',
  'Gaming',
  'Creative & Media',
  'Arts, Audio/Video Technology & Communications',
  ARRAY['Bachelor''s Degree'],
  ARRAY['Video Production', 'Adobe Premiere'],
  '[{"name": "Video Production", "level": 5}, {"name": "Cinematography", "level": 5}, {"name": "Editing", "level": 5}, {"name": "Storytelling", "level": 4}]'::jsonb,
  40000,
  100000,
  62000,
  14.0,
  'Average',
  ARRAY['Film tournaments and team content', 'Edit highlight reels and montages', 'Produce player interviews and features', 'Manage video equipment', 'Collaborate with content team'],
  'Studio, tournament venues, and team facilities. Travel required.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Scriptwriter',
  'Write scripts for broadcast segments, promotional videos, narrative content, and in-game dialogue.',
  'Gaming',
  'Creative & Media',
  'Arts, Audio/Video Technology & Communications',
  ARRAY['Bachelor''s Degree'],
  ARRAY['Creative Writing', 'Screenwriting'],
  '[{"name": "Creative Writing", "level": 5}, {"name": "Storytelling", "level": 5}, {"name": "Research", "level": 4}, {"name": "Collaboration", "level": 4}]'::jsonb,
  40000,
  95000,
  60000,
  12.0,
  'Average',
  ARRAY['Write broadcast scripts and segments', 'Develop narrative content for games', 'Create promotional and marketing copy', 'Collaborate with production team', 'Research and fact-check content'],
  'Office or remote work. Project deadlines.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Photographer',
  'Capture professional photos of players, tournaments, and events for marketing, social media, and press coverage.',
  'Gaming',
  'Creative & Media',
  'Arts, Audio/Video Technology & Communications',
  ARRAY['Bachelor''s Degree', 'Associate''s Degree'],
  ARRAY['Professional Photography', 'Adobe Lightroom'],
  '[{"name": "Photography", "level": 5}, {"name": "Photo Editing", "level": 5}, {"name": "Lighting", "level": 4}, {"name": "Creativity", "level": 5}]'::jsonb,
  35000,
  85000,
  52000,
  10.0,
  'Average',
  ARRAY['Photograph tournaments and events', 'Capture player portraits and action shots', 'Edit and retouch photos', 'Manage photo archive', 'Work with marketing team on content'],
  'Venues, studios, and events. Travel required.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Content Creator',
  'Produce engaging content including streams, videos, social media posts, and community engagement for teams and brands.',
  'Gaming',
  'Creative & Media',
  'Arts, Audio/Video Technology & Communications',
  ARRAY['Bachelor''s Degree', 'High School Diploma'],
  ARRAY['Content Creation', 'Social Media Marketing'],
  '[{"name": "Content Creation", "level": 5}, {"name": "Video Editing", "level": 5}, {"name": "Creativity", "level": 5}, {"name": "Audience Engagement", "level": 5}]'::jsonb,
  30000,
  150000,
  65000,
  35.0,
  'Much faster than average - Content is king',
  ARRAY['Create engaging video and streaming content', 'Manage social media presence', 'Engage with community and fans', 'Collaborate with brands on sponsored content', 'Analyze content performance'],
  'Home studio or office. Flexible but demanding hours.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Influencer',
  'Build and monetize personal brand through streaming, content creation, sponsorships, and community engagement.',
  'Gaming',
  'Creative & Media',
  'Marketing',
  ARRAY['High School Diploma'],
  ARRAY['Personal Branding', 'Content Marketing'],
  '[{"name": "Personal Branding", "level": 5}, {"name": "Entertainment", "level": 5}, {"name": "Community Management", "level": 5}, {"name": "Business Acumen", "level": 4}]'::jsonb,
  0,
  500000,
  55000,
  40.0,
  'Much faster than average - Influencer economy booming',
  ARRAY['Create compelling content daily', 'Build and engage audience', 'Negotiate brand partnerships', 'Manage multiple social platforms', 'Develop personal brand strategy'],
  'Home studio with full control over schedule. Demanding pace.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Game Designer',
  'Design gameplay mechanics, levels, characters, and systems for video games and esports titles.',
  'Gaming',
  'Creative & Technology',
  'Arts, Audio/Video Technology & Communications',
  ARRAY['Bachelor''s Degree'],
  ARRAY['Game Design', 'Unity/Unreal Certified'],
  '[{"name": "Game Design", "level": 5}, {"name": "Level Design", "level": 5}, {"name": "Creativity", "level": 5}, {"name": "Programming", "level": 4}]'::jsonb,
  50000,
  130000,
  75000,
  21.0,
  'Faster than average',
  ARRAY['Design game mechanics and systems', 'Create level layouts and flow', 'Balance gameplay for competitive fairness', 'Prototype and test designs', 'Collaborate with developers and artists'],
  'Game studio. Flexible hours with crunch periods.',
  true,
  CURRENT_DATE
),

-- BROADCAST & PRODUCTION
(
  NULL,
  'Broadcast Engineer',
  'Manage technical aspects of esports broadcasts including streaming, cameras, graphics, and audio mixing.',
  'Gaming',
  'Broadcast & Production',
  'Arts, Audio/Video Technology & Communications',
  ARRAY['Bachelor''s Degree'],
  ARRAY['Broadcast Engineering', 'OBS/vMix Certified'],
  '[{"name": "Broadcasting", "level": 5}, {"name": "Streaming Technology", "level": 5}, {"name": "Troubleshooting", "level": 5}, {"name": "Technical Skills", "level": 5}]'::jsonb,
  50000,
  115000,
  72000,
  20.0,
  'Faster than average',
  ARRAY['Set up and operate broadcast equipment', 'Manage streaming infrastructure', 'Troubleshoot technical issues live', 'Mix audio and video feeds', 'Coordinate with production team'],
  'Broadcast studio or tournament venues. Long hours during events.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Sound Engineer',
  'Design and manage audio for tournaments, broadcasts, content production, and in-game sound.',
  'Gaming',
  'Broadcast & Production',
  'Arts, Audio/Video Technology & Communications',
  ARRAY['Bachelor''s Degree'],
  ARRAY['Audio Engineering', 'Pro Tools Certified'],
  '[{"name": "Audio Engineering", "level": 5}, {"name": "Sound Design", "level": 5}, {"name": "Mixing", "level": 5}, {"name": "Technical Skills", "level": 5}]'::jsonb,
  45000,
  105000,
  65000,
  15.0,
  'Average',
  ARRAY['Mix audio for broadcasts and events', 'Design sound for content and games', 'Manage audio equipment', 'Troubleshoot audio issues', 'Record and edit audio'],
  'Studio, venues, and remote work. Irregular hours.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Lighting Tech',
  'Design and operate lighting for tournaments, broadcasts, and content production to create engaging visual experiences.',
  'Gaming',
  'Broadcast & Production',
  'Arts, Audio/Video Technology & Communications',
  ARRAY['Associate''s Degree', 'Trade School'],
  ARRAY['Lighting Design', 'DMX/LED Systems'],
  '[{"name": "Lighting Design", "level": 5}, {"name": "Technical Operation", "level": 5}, {"name": "Problem Solving", "level": 4}, {"name": "Creativity", "level": 4}]'::jsonb,
  38000,
  82000,
  52000,
  12.0,
  'Average',
  ARRAY['Design lighting for events and broadcasts', 'Operate lighting control systems', 'Install and maintain lighting equipment', 'Create lighting effects and cues', 'Work with production team'],
  'Venues and studios. Physical work with irregular hours.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Production Manager',
  'Oversee all aspects of tournament and broadcast production including crew, equipment, scheduling, and quality.',
  'Gaming',
  'Broadcast & Production',
  'Arts, Audio/Video Technology & Communications',
  ARRAY['Bachelor''s Degree'],
  ARRAY['Production Management', 'Project Management'],
  '[{"name": "Production Management", "level": 5}, {"name": "Leadership", "level": 5}, {"name": "Problem Solving", "level": 5}, {"name": "Budget Management", "level": 4}]'::jsonb,
  55000,
  125000,
  80000,
  18.0,
  'Faster than average',
  ARRAY['Manage broadcast and event production', 'Coordinate crew and equipment', 'Oversee production budget and schedule', 'Ensure quality standards', 'Handle issues and emergencies'],
  'Venues, studios, and office. Long hours during events.',
  true,
  CURRENT_DATE
),

-- MARKETING & COMMUNITY
(
  NULL,
  'Social Media Manager',
  'Manage social media strategy, content, and community engagement for teams, players, and gaming brands.',
  'Gaming',
  'Marketing & Community',
  'Marketing',
  ARRAY['Bachelor''s Degree'],
  ARRAY['Social Media Marketing', 'Digital Marketing'],
  '[{"name": "Social Media Strategy", "level": 5}, {"name": "Content Creation", "level": 5}, {"name": "Community Management", "level": 5}, {"name": "Analytics", "level": 4}]'::jsonb,
  45000,
  100000,
  65000,
  20.0,
  'Faster than average',
  ARRAY['Develop social media strategy', 'Create and schedule content', 'Engage with community and fans', 'Monitor analytics and trends', 'Manage social media campaigns'],
  'Office or remote work. Always-on availability needed.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Community Manager',
  'Build and nurture gaming communities. Moderate discussions, organize events, and serve as liaison between fans and organization.',
  'Gaming',
  'Marketing & Community',
  'Marketing',
  ARRAY['Bachelor''s Degree'],
  ARRAY['Community Management', 'Customer Relations'],
  '[{"name": "Community Building", "level": 5}, {"name": "Communication", "level": 5}, {"name": "Conflict Resolution", "level": 5}, {"name": "Empathy", "level": 5}]'::jsonb,
  40000,
  85000,
  55000,
  18.0,
  'Faster than average',
  ARRAY['Build and engage gaming communities', 'Moderate forums and Discord servers', 'Organize community events', 'Gather feedback and insights', 'Handle community issues'],
  'Office or remote work. Flexible hours with evening/weekend work.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Public Relations Specialist',
  'Manage public image, handle media relations, write press releases, and respond to PR crises for esports organizations.',
  'Gaming',
  'Marketing & Community',
  'Marketing',
  ARRAY['Bachelor''s Degree'],
  ARRAY['Public Relations', 'Crisis Management'],
  '[{"name": "Public Relations", "level": 5}, {"name": "Media Relations", "level": 5}, {"name": "Writing", "level": 5}, {"name": "Crisis Management", "level": 5}]'::jsonb,
  45000,
  110000,
  68000,
  15.0,
  'Average',
  ARRAY['Manage media relations', 'Write press releases and statements', 'Handle PR crises', 'Build relationships with journalists', 'Monitor public sentiment'],
  'Office with flexible hours. On-call for crises.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Sponsorship Coordinator',
  'Identify, negotiate, and manage sponsorship deals and brand partnerships for teams and events.',
  'Gaming',
  'Business & Finance',
  'Business Management & Administration',
  ARRAY['Bachelor''s Degree'],
  ARRAY['Sponsorship Sales', 'Contract Negotiation'],
  '[{"name": "Sales", "level": 5}, {"name": "Negotiation", "level": 5}, {"name": "Relationship Building", "level": 5}, {"name": "Contract Management", "level": 4}]'::jsonb,
  45000,
  120000,
  72000,
  22.0,
  'Faster than average',
  ARRAY['Identify potential sponsors', 'Develop sponsorship proposals', 'Negotiate partnership deals', 'Manage sponsor relationships', 'Ensure deliverable fulfillment'],
  'Office with frequent travel to meet sponsors.',
  true,
  CURRENT_DATE
),

-- BUSINESS & FINANCE
(
  NULL,
  'Accountant',
  'Manage financial records, prepare reports, handle taxes, and ensure compliance for esports organizations.',
  'Gaming',
  'Business & Finance',
  'Finance',
  ARRAY['Bachelor''s Degree'],
  ARRAY['CPA', 'Accounting Certification'],
  '[{"name": "Accounting", "level": 5}, {"name": "Financial Analysis", "level": 5}, {"name": "Tax Preparation", "level": 5}, {"name": "Attention to Detail", "level": 5}]'::jsonb,
  50000,
  110000,
  70000,
  8.0,
  'Average',
  ARRAY['Prepare financial statements', 'Manage accounts and bookkeeping', 'Handle tax compliance', 'Conduct financial audits', 'Provide financial advice'],
  'Office with standard business hours.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Financial Analyst',
  'Analyze financial data, create forecasts, and provide insights to guide business decisions and investments.',
  'Gaming',
  'Business & Finance',
  'Finance',
  ARRAY['Bachelor''s Degree'],
  ARRAY['CFA', 'Financial Modeling'],
  '[{"name": "Financial Analysis", "level": 5}, {"name": "Data Analysis", "level": 5}, {"name": "Forecasting", "level": 5}, {"name": "Excel", "level": 5}]'::jsonb,
  55000,
  125000,
  78000,
  10.0,
  'Average',
  ARRAY['Analyze financial performance', 'Create financial models and forecasts', 'Prepare investment analyses', 'Present findings to management', 'Monitor market trends'],
  'Office with standard business hours.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Business Developer',
  'Identify growth opportunities, develop partnerships, and expand business reach in the gaming industry.',
  'Gaming',
  'Business & Finance',
  'Business Management & Administration',
  ARRAY['Bachelor''s Degree'],
  ARRAY['Business Development', 'Sales'],
  '[{"name": "Business Strategy", "level": 5}, {"name": "Relationship Building", "level": 5}, {"name": "Negotiation", "level": 5}, {"name": "Market Analysis", "level": 4}]'::jsonb,
  50000,
  130000,
  80000,
  15.0,
  'Average',
  ARRAY['Identify business opportunities', 'Develop strategic partnerships', 'Negotiate business deals', 'Analyze market trends', 'Present to stakeholders'],
  'Office with travel for meetings and conferences.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Product Manager',
  'Guide development of gaming products and features from concept to launch based on market research and user needs.',
  'Gaming',
  'Business & Technology',
  'Business Management & Administration',
  ARRAY['Bachelor''s Degree'],
  ARRAY['Product Management', 'Agile Certification'],
  '[{"name": "Product Strategy", "level": 5}, {"name": "Market Research", "level": 5}, {"name": "Roadmap Planning", "level": 5}, {"name": "Leadership", "level": 4}]'::jsonb,
  70000,
  150000,
  95000,
  18.0,
  'Faster than average',
  ARRAY['Define product vision and strategy', 'Conduct market research', 'Create product roadmaps', 'Work with engineering and design', 'Analyze product performance'],
  'Office with flexible hours. Collaborative environment.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Program Manager',
  'Coordinate multiple projects, align teams, manage resources, and ensure successful program delivery.',
  'Gaming',
  'Business & Technology',
  'Business Management & Administration',
  ARRAY['Bachelor''s Degree'],
  ARRAY['PMP', 'Program Management'],
  '[{"name": "Program Management", "level": 5}, {"name": "Coordination", "level": 5}, {"name": "Resource Management", "level": 5}, {"name": "Leadership", "level": 5}]'::jsonb,
  65000,
  135000,
  90000,
  12.0,
  'Average',
  ARRAY['Manage multiple related projects', 'Coordinate across teams', 'Allocate resources effectively', 'Track program progress', 'Report to stakeholders'],
  'Office with flexible hours. High coordination demands.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Project Manager',
  'Plan, execute, and deliver gaming projects on time and budget while managing teams and stakeholders.',
  'Gaming',
  'Business & Technology',
  'Business Management & Administration',
  ARRAY['Bachelor''s Degree'],
  ARRAY['PMP', 'Agile/Scrum Master'],
  '[{"name": "Project Management", "level": 5}, {"name": "Planning", "level": 5}, {"name": "Leadership", "level": 5}, {"name": "Communication", "level": 5}]'::jsonb,
  60000,
  125000,
  82000,
  12.0,
  'Average',
  ARRAY['Plan project scope and timeline', 'Manage project teams', 'Track progress and budget', 'Identify and mitigate risks', 'Communicate with stakeholders'],
  'Office with flexible hours. Some overtime during launches.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'General Manager',
  'Oversee entire esports organization operations, strategy, budgets, and staff to achieve business objectives.',
  'Gaming',
  'Business & Finance',
  'Business Management & Administration',
  ARRAY['Bachelor''s Degree', 'Master''s Degree'],
  ARRAY['MBA', 'Business Management'],
  '[{"name": "Strategic Management", "level": 5}, {"name": "Leadership", "level": 5}, {"name": "Operations", "level": 5}, {"name": "Financial Management", "level": 5}]'::jsonb,
  70000,
  200000,
  115000,
  15.0,
  'Average',
  ARRAY['Set organizational strategy', 'Manage budgets and finances', 'Lead executive team', 'Make high-level decisions', 'Drive business growth'],
  'Office with long hours. High responsibility.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'HR Manager',
  'Manage human resources including recruitment, benefits, employee relations, and compliance for gaming organization.',
  'Gaming',
  'Business & Finance',
  'Business Management & Administration',
  ARRAY['Bachelor''s Degree'],
  ARRAY['SHRM-CP', 'PHR'],
  '[{"name": "Human Resources", "level": 5}, {"name": "Recruitment", "level": 5}, {"name": "Employee Relations", "level": 5}, {"name": "Compliance", "level": 5}]'::jsonb,
  55000,
  115000,
  75000,
  10.0,
  'Average',
  ARRAY['Recruit and onboard talent', 'Manage employee benefits and payroll', 'Handle employee relations issues', 'Ensure legal compliance', 'Develop HR policies'],
  'Office with standard business hours.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Auditor',
  'Review financial records, ensure compliance, identify risks, and provide recommendations for gaming organizations.',
  'Gaming',
  'Business & Finance',
  'Finance',
  ARRAY['Bachelor''s Degree'],
  ARRAY['CIA', 'CPA'],
  '[{"name": "Auditing", "level": 5}, {"name": "Risk Assessment", "level": 5}, {"name": "Compliance", "level": 5}, {"name": "Analytical Thinking", "level": 5}]'::jsonb,
  55000,
  120000,
  78000,
  8.0,
  'Average',
  ARRAY['Conduct financial audits', 'Assess internal controls', 'Identify compliance issues', 'Evaluate operational efficiency', 'Prepare audit reports'],
  'Office with travel to client sites. Standard hours.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Treasurer',
  'Manage cash flow, investments, and financial risk for esports organization. Ensure financial stability.',
  'Gaming',
  'Business & Finance',
  'Finance',
  ARRAY['Bachelor''s Degree', 'Master''s Degree'],
  ARRAY['CTP', 'CFA'],
  '[{"name": "Financial Management", "level": 5}, {"name": "Cash Flow Management", "level": 5}, {"name": "Investment", "level": 5}, {"name": "Risk Management", "level": 5}]'::jsonb,
  65000,
  140000,
  90000,
  8.0,
  'Average',
  ARRAY['Manage organizational cash flow', 'Oversee investments and capital', 'Assess financial risks', 'Prepare financial forecasts', 'Work with banking partners'],
  'Office with standard business hours.',
  true,
  CURRENT_DATE
),

-- OPERATIONS & SUPPORT
(
  NULL,
  'Event Manager',
  'Plan and execute esports tournaments and events from logistics to fan experience.',
  'Gaming',
  'Operations & Events',
  'Hospitality & Tourism',
  ARRAY['Bachelor''s Degree'],
  ARRAY['Event Planning', 'Project Management'],
  '[{"name": "Event Planning", "level": 5}, {"name": "Logistics", "level": 5}, {"name": "Budget Management", "level": 5}, {"name": "Problem Solving", "level": 5}]'::jsonb,
  45000,
  105000,
  68000,
  18.0,
  'Faster than average',
  ARRAY['Plan tournament logistics', 'Coordinate vendors and venues', 'Manage event budget', 'Oversee on-site operations', 'Ensure fan experience quality'],
  'Office and on-site at events. Long hours during tournaments.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Facilities Manager',
  'Manage gaming facilities, arenas, and team houses including maintenance, safety, and operations.',
  'Gaming',
  'Operations & Events',
  'Business Management & Administration',
  ARRAY['Bachelor''s Degree'],
  ARRAY['Facilities Management', 'Safety Certification'],
  '[{"name": "Facilities Management", "level": 5}, {"name": "Safety", "level": 5}, {"name": "Maintenance", "level": 4}, {"name": "Budget Management", "level": 4}]'::jsonb,
  50000,
  95000,
  65000,
  10.0,
  'Average',
  ARRAY['Manage facility operations', 'Coordinate maintenance and repairs', 'Ensure safety compliance', 'Manage facility budget', 'Oversee facility improvements'],
  'On-site at facilities. Standard hours with on-call availability.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Travel Coordinator',
  'Arrange travel logistics for players, staff, and teams including flights, hotels, transportation, and visas.',
  'Gaming',
  'Operations & Events',
  'Hospitality & Tourism',
  ARRAY['Associate''s Degree', 'High School Diploma'],
  ARRAY['Travel Coordination', 'Customer Service'],
  '[{"name": "Travel Planning", "level": 5}, {"name": "Organization", "level": 5}, {"name": "Problem Solving", "level": 5}, {"name": "Communication", "level": 4}]'::jsonb,
  38000,
  70000,
  50000,
  12.0,
  'Average',
  ARRAY['Book flights and accommodations', 'Coordinate team travel schedules', 'Handle travel issues and changes', 'Manage travel budget', 'Arrange visas and documentation'],
  'Office with flexible hours. May need to be available 24/7.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Equipment Manager',
  'Manage gaming equipment, peripherals, and hardware for teams. Ensure everything works properly.',
  'Gaming',
  'Operations & Events',
  'Science, Technology, Engineering & Mathematics',
  ARRAY['Associate''s Degree', 'High School Diploma'],
  ARRAY['Hardware Knowledge', 'Inventory Management'],
  '[{"name": "Equipment Management", "level": 5}, {"name": "Technical Knowledge", "level": 5}, {"name": "Organization", "level": 5}, {"name": "Problem Solving", "level": 4}]'::jsonb,
  40000,
  75000,
  52000,
  10.0,
  'Average',
  ARRAY['Maintain gaming equipment inventory', 'Ensure proper equipment setup', 'Troubleshoot hardware issues', 'Coordinate equipment transport', 'Track equipment maintenance'],
  'Team facility and tournament venues. Flexible hours.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Head Chef',
  'Plan and prepare nutritious meals for esports teams and staff. Manage kitchen operations and dietary needs.',
  'Gaming',
  'Operations & Support',
  'Hospitality & Tourism',
  ARRAY['Associate''s Degree', 'Trade School'],
  ARRAY['Culinary Arts', 'Food Safety'],
  '[{"name": "Culinary Skills", "level": 5}, {"name": "Menu Planning", "level": 5}, {"name": "Kitchen Management", "level": 4}, {"name": "Nutrition", "level": 4}]'::jsonb,
  35000,
  75000,
  48000,
  10.0,
  'Average',
  ARRAY['Plan nutritious meals', 'Prepare team meals', 'Manage kitchen operations', 'Accommodate dietary restrictions', 'Maintain food safety standards'],
  'Team facility kitchen. Flexible schedule around team needs.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Customer Support',
  'Provide customer service to fans, ticket holders, and community members. Handle inquiries and resolve issues.',
  'Gaming',
  'Operations & Support',
  'Business Management & Administration',
  ARRAY['High School Diploma'],
  ARRAY['Customer Service', 'Communication'],
  '[{"name": "Customer Service", "level": 5}, {"name": "Communication", "level": 5}, {"name": "Problem Solving", "level": 4}, {"name": "Patience", "level": 5}]'::jsonb,
  32000,
  55000,
  40000,
  5.0,
  'Slower than average',
  ARRAY['Respond to customer inquiries', 'Resolve customer issues', 'Process orders and refunds', 'Provide information about products', 'Maintain customer records'],
  'Office or remote call center. May include evening/weekend shifts.',
  true,
  CURRENT_DATE
),

-- TALENT & SCOUTING
(
  NULL,
  'Talent Scout',
  'Identify and recruit promising players for professional teams. Evaluate skills and potential.',
  'Esports',
  'Talent & Scouting',
  'Business Management & Administration',
  ARRAY['Bachelor''s Degree'],
  ARRAY['Talent Evaluation', 'Gaming Knowledge'],
  '[{"name": "Talent Evaluation", "level": 5}, {"name": "Game Knowledge", "level": 5}, {"name": "Networking", "level": 5}, {"name": "Negotiation", "level": 4}]'::jsonb,
  40000,
  90000,
  58000,
  22.0,
  'Faster than average',
  ARRAY['Scout amateur players', 'Evaluate player potential', 'Watch tournaments and ladder rankings', 'Build relationships with prospects', 'Coordinate tryouts'],
  'Remote work with extensive online gaming monitoring. Travel to events.',
  true,
  CURRENT_DATE
),

-- JOURNALISM & MEDIA
(
  NULL,
  'Journalist',
  'Report on esports news, write articles, conduct interviews, and cover tournaments for gaming media outlets.',
  'Gaming',
  'Journalism & Media',
  'Arts, Audio/Video Technology & Communications',
  ARRAY['Bachelor''s Degree'],
  ARRAY['Journalism', 'Writing'],
  '[{"name": "Writing", "level": 5}, {"name": "Research", "level": 5}, {"name": "Interviewing", "level": 5}, {"name": "Industry Knowledge", "level": 5}]'::jsonb,
  35000,
  85000,
  52000,
  5.0,
  'Slower than average',
  ARRAY['Write articles and news stories', 'Conduct player and staff interviews', 'Cover tournaments and events', 'Research industry trends', 'Maintain editorial standards'],
  'Office or remote with travel to events. Deadline-driven.',
  true,
  CURRENT_DATE
),

(
  NULL,
  'Lawyer',
  'Provide legal counsel on contracts, intellectual property, compliance, and disputes in the gaming industry.',
  'Gaming',
  'Legal & Compliance',
  'Law, Public Safety, Corrections & Security',
  ARRAY['Doctoral Degree'],
  ARRAY['Bar License', 'Sports Law'],
  '[{"name": "Legal Knowledge", "level": 5}, {"name": "Contract Law", "level": 5}, {"name": "Negotiation", "level": 5}, {"name": "Research", "level": 5}]'::jsonb,
  70000,
  200000,
  115000,
  8.0,
  'Average',
  ARRAY['Review and draft contracts', 'Provide legal counsel', 'Handle disputes and litigation', 'Ensure regulatory compliance', 'Protect intellectual property'],
  'Law firm or in-house. Long hours with high stakes.',
  true,
  CURRENT_DATE
);

-- Add comment
COMMENT ON TABLE public.careers IS 'Esports and gaming industry careers with realistic data';

-- Final count
SELECT
  COUNT(*) as total_careers,
  COUNT(DISTINCT industry) as industries,
  COUNT(DISTINCT sector) as sectors
FROM public.careers
WHERE is_verified = true;
